[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:apache]
command=apache2-foreground
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:flaresolverr]
directory=/flaresolverr
command=python3 -m src.flarestarter
environment=PORT="8191"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

